@startuml
title Use Case Diagram -- Blog: Tangier Inspire Blog

actor "Guest" as Guest
actor "Registered User" as User
actor "Administrator" as Admin
actor "Editor" as Editor

Editor <|-- Admin

rectangle "Tangier Inspire Blog" {
  
  (Log in) as UC_Login
  (View list of articles) as UC1
  (Read article in detail) as UC2
  (Search for an article) as UC3
  (Save an article) as UC4
  (Like & comment & favorite an article) as UC_Like
  (Share an article) as UC5
  (Manage articles) as UC6
}

' Guest interactions (unlogged)
Guest --> UC1
Guest --> UC2
Guest --> UC3
Guest --> UC5

' Registered User interactions (logged-in)
User --> UC_Login
User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC_Like
User --> UC5

' Admin interactions
Admin --> UC_Login
Admin --> UC6

' Extend relationship
UC1 <.. UC2 : <<extend>>

@enduml
